// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	appointmentOrderFieldNames          = builder.RawFieldNames(&AppointmentOrder{})
	appointmentOrderRows                = strings.Join(appointmentOrderFieldNames, ",")
	appointmentOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(appointmentOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	appointmentOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(appointmentOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAppointmentOrderIdPrefix      = "cache:appointmentOrder:id:"
	cacheAppointmentOrderOrderNoPrefix = "cache:appointmentOrder:orderNo:"
)

type (
	appointmentOrderModel interface {
		Insert(ctx context.Context, data *AppointmentOrder) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AppointmentOrder, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*AppointmentOrder, error)
		Update(ctx context.Context, data *AppointmentOrder) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAppointmentOrderModel struct {
		sqlc.CachedConn
		table string
	}

	AppointmentOrder struct {
		Id         uint64    `db:"id"`          // 主键ID
		UserId     uint64    `db:"user_id"`     // 用户ID
		ScheduleId uint64    `db:"schedule_id"` // 场次ID
		OrderNo    string    `db:"order_no"`    // 预约流水号
		Status     uint64    `db:"status"`      // 状态 1:预约成功 2:已取消
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newAppointmentOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAppointmentOrderModel {
	return &defaultAppointmentOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`appointment_order`",
	}
}

func (m *defaultAppointmentOrderModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	appointmentOrderIdKey := fmt.Sprintf("%s%v", cacheAppointmentOrderIdPrefix, id)
	appointmentOrderOrderNoKey := fmt.Sprintf("%s%v", cacheAppointmentOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, appointmentOrderIdKey, appointmentOrderOrderNoKey)
	return err
}

func (m *defaultAppointmentOrderModel) FindOne(ctx context.Context, id uint64) (*AppointmentOrder, error) {
	appointmentOrderIdKey := fmt.Sprintf("%s%v", cacheAppointmentOrderIdPrefix, id)
	var resp AppointmentOrder
	err := m.QueryRowCtx(ctx, &resp, appointmentOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appointmentOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppointmentOrderModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*AppointmentOrder, error) {
	appointmentOrderOrderNoKey := fmt.Sprintf("%s%v", cacheAppointmentOrderOrderNoPrefix, orderNo)
	var resp AppointmentOrder
	err := m.QueryRowIndexCtx(ctx, &resp, appointmentOrderOrderNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", appointmentOrderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, orderNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppointmentOrderModel) Insert(ctx context.Context, data *AppointmentOrder) (sql.Result, error) {
	appointmentOrderIdKey := fmt.Sprintf("%s%v", cacheAppointmentOrderIdPrefix, data.Id)
	appointmentOrderOrderNoKey := fmt.Sprintf("%s%v", cacheAppointmentOrderOrderNoPrefix, data.OrderNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, appointmentOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ScheduleId, data.OrderNo, data.Status)
	}, appointmentOrderIdKey, appointmentOrderOrderNoKey)
	return ret, err
}

func (m *defaultAppointmentOrderModel) Update(ctx context.Context, newData *AppointmentOrder) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	appointmentOrderIdKey := fmt.Sprintf("%s%v", cacheAppointmentOrderIdPrefix, data.Id)
	appointmentOrderOrderNoKey := fmt.Sprintf("%s%v", cacheAppointmentOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, appointmentOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ScheduleId, newData.OrderNo, newData.Status, newData.Id)
	}, appointmentOrderIdKey, appointmentOrderOrderNoKey)
	return err
}

func (m *defaultAppointmentOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAppointmentOrderIdPrefix, primary)
}

func (m *defaultAppointmentOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", appointmentOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAppointmentOrderModel) tableName() string {
	return m.table
}
