// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scheduleFieldNames          = builder.RawFieldNames(&Schedule{})
	scheduleRows                = strings.Join(scheduleFieldNames, ",")
	scheduleRowsExpectAutoSet   = strings.Join(stringx.Remove(scheduleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scheduleRowsWithPlaceHolder = strings.Join(stringx.Remove(scheduleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheScheduleIdPrefix = "cache:schedule:id:"
)

type (
	scheduleModel interface {
		Insert(ctx context.Context, data *Schedule) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Schedule, error)
		Update(ctx context.Context, data *Schedule) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultScheduleModel struct {
		sqlc.CachedConn
		table string
	}

	Schedule struct {
		Id         uint64    `db:"id"`          // 场次ID
		Title      string    `db:"title"`       // 场次名称(如：上午场、XX签证预约)
		TotalSlots int64     `db:"total_slots"` // 总名额数量
		StartTime  time.Time `db:"start_time"`  // 预约开始时间
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newScheduleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultScheduleModel {
	return &defaultScheduleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`schedule`",
	}
}

func (m *defaultScheduleModel) Delete(ctx context.Context, id uint64) error {
	scheduleIdKey := fmt.Sprintf("%s%v", cacheScheduleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, scheduleIdKey)
	return err
}

func (m *defaultScheduleModel) FindOne(ctx context.Context, id uint64) (*Schedule, error) {
	scheduleIdKey := fmt.Sprintf("%s%v", cacheScheduleIdPrefix, id)
	var resp Schedule
	err := m.QueryRowCtx(ctx, &resp, scheduleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scheduleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScheduleModel) Insert(ctx context.Context, data *Schedule) (sql.Result, error) {
	scheduleIdKey := fmt.Sprintf("%s%v", cacheScheduleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, scheduleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.TotalSlots, data.StartTime)
	}, scheduleIdKey)
	return ret, err
}

func (m *defaultScheduleModel) Update(ctx context.Context, data *Schedule) error {
	scheduleIdKey := fmt.Sprintf("%s%v", cacheScheduleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, scheduleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Title, data.TotalSlots, data.StartTime, data.Id)
	}, scheduleIdKey)
	return err
}

func (m *defaultScheduleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheScheduleIdPrefix, primary)
}

func (m *defaultScheduleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scheduleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultScheduleModel) tableName() string {
	return m.table
}
