// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: appointment.proto

// 1. package 决定了在 proto 内部寻址时的命名空间

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 预约抢号的入参
type CreateAppointmentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ScheduleId    int64                  `protobuf:"varint,2,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentReq) Reset() {
	*x = CreateAppointmentReq{}
	mi := &file_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentReq) ProtoMessage() {}

func (x *CreateAppointmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentReq.ProtoReflect.Descriptor instead.
func (*CreateAppointmentReq) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAppointmentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAppointmentReq) GetScheduleId() int64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

// 预约抢号的出参
type CreateAppointmentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentResp) Reset() {
	*x = CreateAppointmentResp{}
	mi := &file_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentResp) ProtoMessage() {}

func (x *CreateAppointmentResp) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentResp.ProtoReflect.Descriptor instead.
func (*CreateAppointmentResp) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppointmentResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAppointmentResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateAppointmentResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type PreloadScheduleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    uint64                 `protobuf:"varint,1,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreloadScheduleReq) Reset() {
	*x = PreloadScheduleReq{}
	mi := &file_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreloadScheduleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadScheduleReq) ProtoMessage() {}

func (x *PreloadScheduleReq) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadScheduleReq.ProtoReflect.Descriptor instead.
func (*PreloadScheduleReq) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *PreloadScheduleReq) GetScheduleId() uint64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

type PreloadScheduleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreloadScheduleResp) Reset() {
	*x = PreloadScheduleResp{}
	mi := &file_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreloadScheduleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadScheduleResp) ProtoMessage() {}

func (x *PreloadScheduleResp) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadScheduleResp.ProtoReflect.Descriptor instead.
func (*PreloadScheduleResp) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *PreloadScheduleResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PreloadScheduleResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_appointment_proto protoreflect.FileDescriptor

const file_appointment_proto_rawDesc = "" +
	"\n" +
	"\x11appointment.proto\x12\vappointment\"N\n" +
	"\x14CreateAppointmentReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"scheduleId\x18\x02 \x01(\x03R\n" +
	"scheduleId\"W\n" +
	"\x15CreateAppointmentResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\aorderNo\x18\x03 \x01(\tR\aorderNo\"4\n" +
	"\x12PreloadScheduleReq\x12\x1e\n" +
	"\n" +
	"scheduleId\x18\x01 \x01(\x04R\n" +
	"scheduleId\";\n" +
	"\x13PreloadScheduleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xbf\x01\n" +
	"\vAppointment\x12Z\n" +
	"\x11CreateAppointment\x12!.appointment.CreateAppointmentReq\x1a\".appointment.CreateAppointmentResp\x12T\n" +
	"\x0fPreloadSchedule\x12\x1f.appointment.PreloadScheduleReq\x1a .appointment.PreloadScheduleRespB\x06Z\x04./pbb\x06proto3"

var (
	file_appointment_proto_rawDescOnce sync.Once
	file_appointment_proto_rawDescData []byte
)

func file_appointment_proto_rawDescGZIP() []byte {
	file_appointment_proto_rawDescOnce.Do(func() {
		file_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appointment_proto_rawDesc), len(file_appointment_proto_rawDesc)))
	})
	return file_appointment_proto_rawDescData
}

var file_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_appointment_proto_goTypes = []any{
	(*CreateAppointmentReq)(nil),  // 0: appointment.CreateAppointmentReq
	(*CreateAppointmentResp)(nil), // 1: appointment.CreateAppointmentResp
	(*PreloadScheduleReq)(nil),    // 2: appointment.PreloadScheduleReq
	(*PreloadScheduleResp)(nil),   // 3: appointment.PreloadScheduleResp
}
var file_appointment_proto_depIdxs = []int32{
	0, // 0: appointment.Appointment.CreateAppointment:input_type -> appointment.CreateAppointmentReq
	2, // 1: appointment.Appointment.PreloadSchedule:input_type -> appointment.PreloadScheduleReq
	1, // 2: appointment.Appointment.CreateAppointment:output_type -> appointment.CreateAppointmentResp
	3, // 3: appointment.Appointment.PreloadSchedule:output_type -> appointment.PreloadScheduleResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_appointment_proto_init() }
func file_appointment_proto_init() {
	if File_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appointment_proto_rawDesc), len(file_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appointment_proto_goTypes,
		DependencyIndexes: file_appointment_proto_depIdxs,
		MessageInfos:      file_appointment_proto_msgTypes,
	}.Build()
	File_appointment_proto = out.File
	file_appointment_proto_goTypes = nil
	file_appointment_proto_depIdxs = nil
}
