// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: appointment.proto

// 1. package 决定了在 proto 内部寻址时的命名空间

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Appointment_CreateAppointment_FullMethodName = "/appointment.Appointment/CreateAppointment"
)

// AppointmentClient is the client API for Appointment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 核心预约 RPC 服务接口
type AppointmentClient interface {
	CreateAppointment(ctx context.Context, in *CreateAppointmentReq, opts ...grpc.CallOption) (*CreateAppointmentResp, error)
}

type appointmentClient struct {
	cc grpc.ClientConnInterface
}

func NewAppointmentClient(cc grpc.ClientConnInterface) AppointmentClient {
	return &appointmentClient{cc}
}

func (c *appointmentClient) CreateAppointment(ctx context.Context, in *CreateAppointmentReq, opts ...grpc.CallOption) (*CreateAppointmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAppointmentResp)
	err := c.cc.Invoke(ctx, Appointment_CreateAppointment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppointmentServer is the server API for Appointment service.
// All implementations must embed UnimplementedAppointmentServer
// for forward compatibility.
//
// 核心预约 RPC 服务接口
type AppointmentServer interface {
	CreateAppointment(context.Context, *CreateAppointmentReq) (*CreateAppointmentResp, error)
	mustEmbedUnimplementedAppointmentServer()
}

// UnimplementedAppointmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppointmentServer struct{}

func (UnimplementedAppointmentServer) CreateAppointment(context.Context, *CreateAppointmentReq) (*CreateAppointmentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAppointment not implemented")
}
func (UnimplementedAppointmentServer) mustEmbedUnimplementedAppointmentServer() {}
func (UnimplementedAppointmentServer) testEmbeddedByValue()                     {}

// UnsafeAppointmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppointmentServer will
// result in compilation errors.
type UnsafeAppointmentServer interface {
	mustEmbedUnimplementedAppointmentServer()
}

func RegisterAppointmentServer(s grpc.ServiceRegistrar, srv AppointmentServer) {
	// If the following call panics, it indicates UnimplementedAppointmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Appointment_ServiceDesc, srv)
}

func _Appointment_CreateAppointment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppointmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppointmentServer).CreateAppointment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appointment_CreateAppointment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppointmentServer).CreateAppointment(ctx, req.(*CreateAppointmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Appointment_ServiceDesc is the grpc.ServiceDesc for Appointment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Appointment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appointment.Appointment",
	HandlerType: (*AppointmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAppointment",
			Handler:    _Appointment_CreateAppointment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appointment.proto",
}
