// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: appointment.proto

package appointment

import (
	"context"

	"github.com/czm-curtis/smart-reserve/apps/appointment/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAppointmentReq  = pb.CreateAppointmentReq
	CreateAppointmentResp = pb.CreateAppointmentResp

	Appointment interface {
		CreateAppointment(ctx context.Context, in *CreateAppointmentReq, opts ...grpc.CallOption) (*CreateAppointmentResp, error)
	}

	defaultAppointment struct {
		cli zrpc.Client
	}
)

func NewAppointment(cli zrpc.Client) Appointment {
	return &defaultAppointment{
		cli: cli,
	}
}

func (m *defaultAppointment) CreateAppointment(ctx context.Context, in *CreateAppointmentReq, opts ...grpc.CallOption) (*CreateAppointmentResp, error) {
	client := pb.NewAppointmentClient(m.cli.Conn())
	return client.CreateAppointment(ctx, in, opts...)
}
