// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AppointmentReq struct {
	UserId     int64 `json:"userId"`     // 用户ID
	ScheduleId int64 `json:"scheduleId"` // 预约排班/放号场次ID
}

type AppointmentResp struct {
	Code    int    `json:"code"`    // 状态码：0-成功，其他-失败
	Msg     string `json:"msg"`     // 错误提示信息
	OrderNo string `json:"orderNo"` // 预约成功后的流水号/单号
}
