// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AppointmentReq struct {
	UserId     int64 `json:"userId"`
	ScheduleId int64 `json:"scheduleId"`
}

type AppointmentResp struct {
	Code    int    `json:"code"`
	Msg     string `json:"msg"`
	OrderNo string `json:"orderNo"`
}
