// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: appointment.proto

package server

import (
	"context"

	"github.com/czm-curtis/smart-reserve/apps/appointment/rpc/internal/logic"
	"github.com/czm-curtis/smart-reserve/apps/appointment/rpc/internal/svc"
	"github.com/czm-curtis/smart-reserve/apps/appointment/rpc/pb"
)

type AppointmentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAppointmentServer
}

func NewAppointmentServer(svcCtx *svc.ServiceContext) *AppointmentServer {
	return &AppointmentServer{
		svcCtx: svcCtx,
	}
}

func (s *AppointmentServer) CreateAppointment(ctx context.Context, in *pb.CreateAppointmentReq) (*pb.CreateAppointmentResp, error) {
	l := logic.NewCreateAppointmentLogic(ctx, s.svcCtx)
	return l.CreateAppointment(in)
}

func (s *AppointmentServer) PreloadSchedule(ctx context.Context, in *pb.PreloadScheduleReq) (*pb.PreloadScheduleResp, error) {
	l := logic.NewPreloadScheduleLogic(ctx, s.svcCtx)
	return l.PreloadSchedule(in)
}
