// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: appointment.proto

package server

import (
	"context"

	"github.com/czm-curtis/smart-reserve/apps/appointment/rpc/appointmentclient"
	"github.com/czm-curtis/smart-reserve/apps/appointment/rpc/internal/logic"
	"github.com/czm-curtis/smart-reserve/apps/appointment/rpc/internal/svc"
)

type AppointmentServer struct {
	svcCtx *svc.ServiceContext
	appointmentclient.UnimplementedAppointmentServer
}

func NewAppointmentServer(svcCtx *svc.ServiceContext) *AppointmentServer {
	return &AppointmentServer{
		svcCtx: svcCtx,
	}
}

func (s *AppointmentServer) CreateAppointment(ctx context.Context, in *appointmentclient.CreateAppointmentReq) (*appointmentclient.CreateAppointmentResp, error) {
	l := logic.NewCreateAppointmentLogic(ctx, s.svcCtx)
	return l.CreateAppointment(in)
}
